function t121_setHeight(recid){var rec=jQuery('#rec'+recid);var div=jQuery('#youtubeiframe'+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height);var videoLazy=rec.find('.t-video-lazyload');if(videoLazy!==undefined){var iframeLazy=videoLazy.find('iframe');var heightLazy=videoLazy.width()*0.5625;videoLazy.height(heightLazy);iframeLazy.height(heightLazy);setTimeout(function(){div=jQuery('#youtubeiframe'+recid);div.height(div.width()*0.5625)},200)}}
function t142_checkSize(recid){var el=jQuery("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed")}}}
function t199_showMenu(recid){var el=jQuery('#rec'+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=jQuery(this),$body=jQuery('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=jQuery(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){jQuery(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$menu.find('.t199__menu-item-wrap .t-menusub__link-item').each(function(){var curUrl=jQuery(this).attr('href');jQuery(this).on('click',function(e){$body.removeClass(CLASS_MENU)})});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});jQuery(document).on('click',function(e){var clickedInsideMenu=jQuery(e.target).hasClass('t199__js__menu')||jQuery(e.target).parents('.t199__js__menu').length>0;if(!clickedInsideMenu){$body.removeClass(CLASS_MENU)}})});jQuery('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){jQuery('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=jQuery('#rec'+recid);var $header=el.find('.t199__js__header');var bgcolor=$header.css('background-color');var isScrolling=!1;var CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if(jQuery(window).scrollTop()>0){$header.addClass(CLASS_ACTIVE);$header.css('background-color','')}else{$header.removeClass(CLASS_ACTIVE);$header.css('background-color',bgcolor)}}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);jQuery(window).on('scroll',updateHeader);updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
jQuery(".t199__menu a[href='"+url+"']").addClass('t-active');jQuery(".t199__menu a[href='"+url+"/']").addClass('t-active');jQuery(".t199__menu a[href='"+pathname+"']").addClass('t-active');jQuery(".t199__menu a[href='/"+pathname+"']").addClass('t-active');jQuery(".t199__menu a[href='"+pathname+"/']").addClass('t-active');jQuery(".t199__menu a[href='/"+pathname+"/']").addClass('t-active')}
function t199_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t199_navLinks=jQuery('#rec'+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=jQuery(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref(jQuery(this));if(typeof t199_cursection.attr('id')!='undefined'){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr('id')]=jQuery(this)});t199_updateSectionsOffsets(t199_sections);jQuery(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));jQuery('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!jQuery(this).hasClass('tooltipstered')){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref(jQuery(this)).attr('id')].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref(jQuery(this)).attr('id')}});jQuery(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<t199_lastCall+t199_interval){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t199_curSection=jQuery(this);t199_curSection.attr('data-offset-top',t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return jQuery(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return jQuery(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=jQuery(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr('data-offset-top')>t199_scrollPosition+300){t199_navLinks.removeClass('t-active');return null}
jQuery(t199_sections).each(function(e){var t199_curSection=jQuery(this),t199_sectionTop=t199_curSection.attr('data-offset-top'),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(t199_scrollPosition+300>=t199_sectionTop||(t199_sections[0].attr('id')==t199_id&&t199_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t229__list_item a[href='"+url+"']").addClass("t-active");jQuery(".t229__list_item a[href='"+url+"/']").addClass("t-active");jQuery(".t229__list_item a[href='"+pathname+"']").addClass("t-active");jQuery(".t229__list_item a[href='/"+pathname+"']").addClass("t-active");jQuery(".t229__list_item a[href='"+pathname+"/']").addClass("t-active");jQuery(".t229__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t229_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t229_navLinks=jQuery("#rec"+recid+" .t229__list_item a:not(.tooltipstered)[href*='#']");if(t229_navLinks.length>0){t229_catchScroll(t229_navLinks)}}}
function t229_catchScroll(t229_navLinks){var t229_clickedSectionId=null,t229_sections=new Array(),t229_sectionIdTonavigationLink=[],t229_interval=100,t229_lastCall,t229_timeoutId;t229_navLinks=jQuery(t229_navLinks.get().reverse());t229_navLinks.each(function(){var t229_cursection=t229_getSectionByHref(jQuery(this));if(typeof t229_cursection.attr("id")!="undefined"){t229_sections.push(t229_cursection)}
t229_sectionIdTonavigationLink[t229_cursection.attr("id")]=jQuery(this)});t229_updateSectionsOffsets(t229_sections);t229_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});jQuery(window).bind('resize',t_throttle(function(){t229_updateSectionsOffsets(t229_sections)},200));jQuery('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(t229_sections)});setInterval(function(){t229_updateSectionsOffsets(t229_sections)},5000);t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId);t229_navLinks.click(function(){var t229_clickedSection=t229_getSectionByHref(jQuery(this));if(!jQuery(this).hasClass("tooltipstered")&&typeof t229_clickedSection.attr("id")!="undefined"){t229_navLinks.removeClass('t-active');jQuery(this).addClass('t-active');t229_clickedSectionId=t229_getSectionByHref(jQuery(this)).attr("id")}});jQuery(window).scroll(function(){var t229_now=new Date().getTime();if(t229_lastCall&&t229_now<(t229_lastCall+t229_interval)){clearTimeout(t229_timeoutId);t229_timeoutId=setTimeout(function(){t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)},t229_interval-(t229_now-t229_lastCall))}else{t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)}})}
function t229_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t229_curSection=jQuery(this);t229_curSection.attr("data-offset-top",t229_curSection.offset().top)})}
function t229_getSectionByHref(curlink){var t229_curLinkValue=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return jQuery(".r[id='"+t229_curLinkValue+"']")}else{return jQuery(".r[data-record-type='215']").has("a[name='"+t229_curLinkValue+"']")}}
function t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId){var t229_scrollPosition=jQuery(window).scrollTop(),t229_valueToReturn=t229_clickedSectionId;if(t229_sections.length!=0&&t229_clickedSectionId==null&&t229_sections[t229_sections.length-1].attr("data-offset-top")>(t229_scrollPosition+300)){t229_navLinks.removeClass('t-active');return null}
jQuery(t229_sections).each(function(e){var t229_curSection=jQuery(this),t229_sectionTop=t229_curSection.attr("data-offset-top"),t229_id=t229_curSection.attr('id'),t229_navLink=t229_sectionIdTonavigationLink[t229_id];if(((t229_scrollPosition+300)>=t229_sectionTop)||(t229_sections[0].attr("id")==t229_id&&t229_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t229_clickedSectionId==null&&!t229_navLink.hasClass('t-active')){t229_navLinks.removeClass('t-active');t229_navLink.addClass('t-active');t229_valueToReturn=null}else{if(t229_clickedSectionId!=null&&t229_id==t229_clickedSectionId){t229_valueToReturn=null}}
return!1}});return t229_valueToReturn}
function t229_setPath(pageid){}
function t229_setBg(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t229").each(function(){var el=jQuery(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{jQuery(".t229").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t229_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery("#rec"+recid+" .t229").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t229_changeBgOpacityMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t229").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll)}else{el.css("background-color",bgcolor)}})}}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=jQuery('html, body');var target="";if(speed===undefined){speed=400}
try{target=jQuery(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=jQuery('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean(jQuery('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t381_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t381").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("visibility","visible");el.animate({"opacity":"1"},300,function(){})}}else{el.stop();el.css("visibility","hidden")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if(jQuery(window).scrollTop()+jQuery(window).height()>=jQuery(document).height()-hideoffset){if(el.css('visibility')!='hidden'){el.finish();el.css("visibility","hidden")}}else{if(appearoffset!=""){if(jQuery(window).scrollTop()>=appearoffset){el.stop();el.css("visibility","visible")}}else{el.stop();el.css("visibility","visible")}}}})}}
function t389_scrollToTop(){jQuery('html, body').animate({scrollTop:0},700)}
function t396_init(recid){var data='';var res=t396_detectResolution();var ab=jQuery('#rec'+recid).find('.t396__artboard');window.tn_window_width=jQuery(window).width();window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;t396_initTNobj();t396_switchResolution(res);t396_updateTNobj();t396_artboard_build(data,recid);jQuery(window).resize(function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if($isMobile){var ww=jQuery(window).width();if(ww!=window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});jQuery(window).on("orientationchange",function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});jQuery(window).on('load',function(){t396_allelems__renderView(ab);if(typeof t_lazyload_update==='function'&&ab.css('overflow')==='auto'){ab.bind('scroll',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&ab.css('overflow')==='visible'){ab.css('overflow','hidden');setTimeout(function(){ab.css('overflow','visible')},1)}});var rec=jQuery('#rec'+recid);if(rec.attr('data-connect-with-tab')=='yes'){rec.find('.t396').bind('displayChanged',function(){var ab=rec.find('.t396__artboard');t396_allelems__renderView(ab)})}
if(isSafari)rec.find('.t396').addClass('t396_safari');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_getRotateValue(matrix){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var c=values[2];var d=values[3];var scale=Math.sqrt(a*a+b*b);var sin=b/scale;var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));return angle}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var isOpera=(!!window.opr&&!!opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var res=t396_detectResolution();var rec=jQuery('#rec'+recid);var $ab=rec.find('.t396__artboard');var abWidth=$ab.width();var updatedBlockHeight=Math.floor($ab.height()*window.tn_scale_factor);var ab_height_vh=t396_ab__getFieldValue($ab,'height_vh');window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;if(ab_height_vh!=''){var ab_min_height=t396_ab__getFieldValue($ab,'height');var ab_max_height=t396_ab__getHeight($ab);var scaledMinHeight=ab_min_height*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=ab_max_height)?scaledMinHeight:ab_max_height}
$ab.addClass('t396__artboard_scale');var scaleStr=isOnlyScalable?('transform: scale('+window.tn_scale_factor+') !important;'):('zoom: '+window.tn_scale_factor+';');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'<style>';$ab.append(styleStr);rec.find('.t396__elem').each(function(){var $el=jQuery(this);var containerProp=t396_elem__getFieldValue($el,'container');if(containerProp==='grid'){if(isOnlyScalable){var scaleProp='scale('+window.tn_scale_factor+')';var transformMatrix=$el.find('.tn-atom').css('transform');var rotatation=(transformMatrix&&transformMatrix!=='none')?t396_getRotateValue(transformMatrix):null;if(rotatation){if(!$el.find('.tn-atom__sbs-anim-wrapper').length)$el.find('.tn-atom').css('transform-origin','center');scaleProp=scaleProp+' rotate('+rotatation+'deg)'}
$el.find('.tn-atom').css('transform',scaleProp)}else{$el.css('zoom',window.tn_scale_factor);if($el.attr('data-elem-type')==='text'&&res<1200)$el.find('.tn-atom').css('-webkit-text-size-adjust','auto');$el.find('.tn-atom').css('transform-origin','center')}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var ww;var rec=jQuery('#rec'+recid);if($isMobile){ww=jQuery(window).width()}else{ww=window.innerWidth}
var res=t396_detectResolution();rec.find('.t396__scale-style').remove();if(!isOnlyScalable){rec.find('.t396__elem').css('zoom','');rec.find('.t396__elem .tn-atom').css('transform-origin','')}
var ab=rec.find('.t396__artboard');var abWidth=ab.width();window.tn_window_width=ww;window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;t396_switchResolution(res);t396_updateTNobj();t396_ab__renderView(ab);t396_allelems__renderView(ab);var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_detectResolution(){var ww;if($isMobile){ww=jQuery(window).width()}else{ww=window.innerWidth}
var res;res=1200;if(ww<1200){res=960}
if(ww<960){res=640}
if(ww<640){res=480}
if(ww<480){res=320}
return(res)}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=["320","480","640","960","1200"];window.tn.canvas_max_sizes=["480","640","960","1200",""];window.tn.ab_fields=["height","width","bgcolor","bgimg","bgattachment","bgposition","filteropacity","filtercolor","filteropacity2","filtercolor2","height_vh","valign"]}
function t396_updateTNobj(){tn_console('func: updateTNobj');if(typeof window.zero_window_width_hook!='undefined'&&window.zero_window_width_hook=='allrecords'&&jQuery('#allrecords').length){window.tn.window_width=parseInt(jQuery('#allrecords').width())}else{window.tn.window_width=parseInt(jQuery(window).width())}
if($isMobile){window.tn.window_height=parseInt(jQuery(window).height())}else{window.tn.window_height=parseInt(window.innerHeight)}
if(window.tn.curResolution==1200){window.tn.canvas_min_width=1200;window.tn.canvas_max_width=window.tn.window_width}
if(window.tn.curResolution==960){window.tn.canvas_min_width=960;window.tn.canvas_max_width=1200}
if(window.tn.curResolution==640){window.tn.canvas_min_width=640;window.tn.canvas_max_width=960}
if(window.tn.curResolution==480){window.tn.canvas_min_width=480;window.tn.canvas_max_width=640}
if(window.tn.curResolution==320){window.tn.canvas_min_width=320;window.tn.canvas_max_width=480}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=parseFloat((window.tn.window_width-window.tn.grid_width)/2)}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId="Don't call this twice without a uniqueId"}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(res,resmax){tn_console('func: switchResolution');if(typeof resmax=='undefined'){if(res==1200)resmax='';if(res==960)resmax=1200;if(res==640)resmax=960;if(res==480)resmax=640;if(res==320)resmax=480}
window.tn.curResolution=res;window.tn.curResolution_max=resmax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var ab=jQuery('#rec'+recid).find('.t396__artboard');t396_ab__renderView(ab);ab.find('.tn-elem').each(function(){var item=jQuery(this);if(item.attr('data-elem-type')=='text'){t396_addText(ab,item)}
if(item.attr('data-elem-type')=='image'){t396_addImage(ab,item)}
if(item.attr('data-elem-type')=='shape'){t396_addShape(ab,item)}
if(item.attr('data-elem-type')=='button'){t396_addButton(ab,item)}
if(item.attr('data-elem-type')=='video'){t396_addVideo(ab,item)}
if(item.attr('data-elem-type')=='html'){t396_addHtml(ab,item)}
if(item.attr('data-elem-type')=='tooltip'){t396_addTooltip(ab,item)}
if(item.attr('data-elem-type')=='form'){t396_addForm(ab,item)}
if(item.attr('data-elem-type')=='gallery'){t396_addGallery(ab,item)}});jQuery('#rec'+recid).find('.t396__artboard').removeClass('rendering').addClass('rendered');if(ab.attr('data-artboard-ovrflw')=='visible'){jQuery('#allrecords').css('overflow','hidden')}
if($isMobile){jQuery('#rec'+recid).append('<style>@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}</style>')}}
function t396_ab__renderView(ab){var fields=window.tn.ab_fields;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(ab,fields[i])}
var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(isScaled&&!isTildaModeEdit&&ab_height_vh!='')var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor;var offset_top=0;if(ab_min_height==ab_max_height||(scaledMinHeight&&scaledMinHeight>=ab_max_height)){offset_top=0}else{var ab_valign=t396_ab__getFieldValue(ab,'valign');if(ab_valign=='top'){offset_top=0}else if(ab_valign=='center'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)/2).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)/2).toFixed(1)}}else if(ab_valign=='bottom'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)).toFixed(1)}}else if(ab_valign=='stretch'){offset_top=0;ab_min_height=ab_max_height}else{offset_top=0}}
ab.attr('data-artboard-proxy-min-offset-top',offset_top);ab.attr('data-artboard-proxy-min-height',ab_min_height);ab.attr('data-artboard-proxy-max-height',ab_max_height);var filter=ab.find('.t396__filter');var carrier=ab.find('.t396__carrier');var abHeightVh=t396_ab__getFieldValue(ab,'height_vh');abHeightVh=parseFloat(abHeightVh);if(window.isMobile&&abHeightVh){var height=document.documentElement.clientHeight*parseFloat(abHeightVh/100);ab.css('height',height);filter.css('height',height);carrier.css('height',height)}}
function t396_addText(ab,el){tn_console('func: addText');var fields_str='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addImage(ab,el){tn_console('func: addImage');var fields_str='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);el.find('img').on("load",function(){t396_elem__renderViewOneField(el,'top');if(typeof jQuery(this).attr('src')!='undefined'&&jQuery(this).attr('src')!=''){setTimeout(function(){t396_elem__renderViewOneField(el,'top')},2000)}}).each(function(){if(this.complete)jQuery(this).trigger('load')});el.find('img').on('tuwidget_done',function(e,file){t396_elem__renderViewOneField(el,'top')})}
function t396_addShape(ab,el){tn_console('func: addShape');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addButton(ab,el){tn_console('func: addButton');var fields_str='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);return(el)}
function t396_addVideo(ab,el){tn_console('func: addVideo');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var viel=el.find('.tn-atom__videoiframe');var viatel=el.find('.tn-atom');viatel.css('background-color','#000');var vihascover=viatel.attr('data-atom-video-has-cover');if(typeof vihascover=='undefined'){vihascover=''}
if(vihascover=='y'){viatel.click(function(){var viifel=viel.find('iframe');if(viifel.length){var foo=viifel.attr('data-original');viifel.attr('src',foo)}
viatel.css('background-image','none');viatel.find('.tn-atom__video-play-link').css('display','none')})}
var autoplay=t396_elem__getFieldValue(el,'autoplay');var showinfo=t396_elem__getFieldValue(el,'showinfo');var loop=t396_elem__getFieldValue(el,'loop');var mute=t396_elem__getFieldValue(el,'mute');var startsec=t396_elem__getFieldValue(el,'startsec');var endsec=t396_elem__getFieldValue(el,'endsec');var tmode=jQuery('#allrecords').attr('data-tilda-mode');var url='';var viyid=viel.attr('data-youtubeid');if(typeof viyid!='undefined'&&viyid!=''){url='//youtube.com/embed/';url+=viyid+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo=='y'?'1':'0');if(loop=='y'){url+='&loop=1&playlist='+viyid}
if(startsec>0){url+='&start='+startsec}
if(endsec>0){url+='&end='+endsec}
if(mute=='y'){url+='&mute=1'}
if(vihascover=='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
viel.html('<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>');if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}
if(autoplay=='y'&&mute=='y'){viatel.trigger('click')}}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>')}}}
var vivid=viel.attr('data-vimeoid');if(typeof vivid!='undefined'&&vivid>0){url='//player.vimeo.com/video/';url+=vivid+'?color=ffffff&badge=0';if(showinfo=='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop=='y'){url+='&loop=1'}
if(mute=='y'){url+='&muted=1'}
if(vihascover=='y'){url+='&autoplay=1';viel.html('<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}}}}
function t396_addHtml(ab,el){tn_console('func: addHtml');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addTooltip(ab,el){tn_console('func: addTooltip');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var pinEl=el.find('.tn-atom__pin');var tipEl=el.find('.tn-atom__tip');var tipopen=el.attr('data-field-tipopen-value');if(isMobile||(typeof tipopen!='undefined'&&tipopen=='click')){t396_setUpTooltip_mobile(el,pinEl,tipEl)}else{t396_setUpTooltip_desktop(el,pinEl,tipEl)}
setTimeout(function(){jQuery('.tn-atom__tip-img').each(function(){var foo=jQuery(this).attr('data-tipimg-original');if(typeof foo!='undefined'&&foo!=''){jQuery(this).attr('src',foo)}})},3000)}
function t396_addForm(ab,el){tn_console('func: addForm');var fields_str='width,top,left,';fields_str+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addGallery(ab,el){tn_console('func: addForm');var fields_str='width,height,top,left,';fields_str+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_elem__setFieldValue(el,prop,val,flag_render,flag_updateui,res){if(res=='')res=window.tn.curResolution;if(res<1200&&prop!='zindex'){el.attr('data-field-'+prop+'-res-'+res+'-value',val)}else{el.attr('data-field-'+prop+'-value',val)}
if(flag_render=='render')elem__renderViewOneField(el,prop);if(flag_updateui=='updateui')panelSettings__updateUi(el,prop,val)}
function t396_elem__getFieldValue(el,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}
if(res==640){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}
if(res==480){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}
if(res==320){r=el.attr('data-field-'+prop+'-res-320-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}}}else{r=el.attr('data-field-'+prop+'-value')}
return(r)}
function t396_elem__renderView(el){tn_console('func: elem__renderView');var fields=el.attr('data-fields');if(!fields){return!1}
fields=fields.split(',');for(var i=0;i<fields.length;i++){t396_elem__renderViewOneField(el,fields[i])}}
function t396_elem__renderViewOneField(el,field){var value=t396_elem__getFieldValue(el,field);if(field=='left'){value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('left',parseFloat(value).toFixed(1)+'px')}
if(field=='top'){var ab=el.parents('.t396__artboard');value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('top',parseFloat(value).toFixed(1)+'px')}
if(field=='width'){value=t396_elem__getWidth(el,value);el.css('width',parseFloat(value).toFixed(1)+'px');var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){var pinSvgIcon=el.find('.tn-atom__pin-icon');if(pinSvgIcon.length>0){var pinSize=parseFloat(value).toFixed(1)+'px';pinSvgIcon.css({'width':pinSize,'height':pinSize})}
el.css('height',parseInt(value).toFixed(1)+'px')}
if(eltype=='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('width',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('width',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('width',parseFloat(value).toFixed(1)+'px')}}
if(field=='height'){var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){return}
value=t396_elem__getHeight(el,value);el.css('height',parseFloat(value).toFixed(1)+'px');if(eltype==='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('height',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('height',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('height',parseFloat(value).toFixed(1)+'px')}}
if(field=='container'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='width'||field=='height'||field=='fontsize'||field=='fontfamily'||field=='letterspacing'||field=='fontweight'||field=='img'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='inputs'){value=el.find('.tn-atom__inputs-textarea').val();try{t_zeroForms__renderForm(el,value)}catch(err){}}}
function t396_elem__convertPosition__Local__toAbsolute(el,field,value){var ab=el.parents('.t396__artboard');var blockVAlign=t396_ab__getFieldValue(ab,'valign');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var el_axisy=t396_elem__getFieldValue(el,'axisy');value=parseInt(value);if(field=='left'){var el_container,offset_left,el_container_width,el_width;var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_left=window.tn.grid_offset_left;el_container_width=window.tn.grid_width}else{el_container='window';offset_left=0;el_container_width=window.tn.window_width}
var el_leftunits=t396_elem__getFieldValue(el,'leftunits');if(el_leftunits==='%'){value=t396_roundFloat(el_container_width*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offset_left+value}
var el_axisx=t396_elem__getFieldValue(el,'axisx');if(el_axisx==='center'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width/2-el_width/2+value}
if(el_axisx==='right'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width-el_width+value}}
if(field==='top'){var el_container,offset_top,el_container_height,el_height;var ab=el.parent();var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_top=parseFloat(ab.attr('data-artboard-proxy-min-offset-top'));el_container_height=parseFloat(ab.attr('data-artboard-proxy-min-height'))}else{el_container='window';offset_top=0;el_container_height=parseFloat(ab.attr('data-artboard-proxy-max-height'))}
var el_topunits=t396_elem__getFieldValue(el,'topunits');if(el_topunits==='%'){value=(el_container_height*(value/100))}
if(isScaledElement&&el_container!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&el_container!=='window'){offset_top=blockVAlign==='stretch'?0:(offset_top/window.tn_scale_factor)}
value=offset_top+value;var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);if(isScaled&&!isTildaModeEdit&&ab_height_vh!=''){var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor}
if(el_axisy==='center'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height/2-el_height/2+value}
if(el_axisy==='bottom'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height-el_height+value}}
return(value)}
function t396_ab__setFieldValue(ab,prop,val,res){if(res=='')res=window.tn.curResolution;if(res<1200){ab.attr('data-artboard-'+prop+'-res-'+res,val)}else{ab.attr('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(ab,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}
if(res==640){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}
if(res==480){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}
if(res==320){r=ab.attr('data-artboard-'+prop+'-res-320');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}}}else{r=ab.attr('data-artboard-'+prop)}
return(r)}
function t396_ab__renderViewOneField(ab,field){var value=t396_ab__getFieldValue(ab,field)}
function t396_allelems__renderView(ab){tn_console('func: allelems__renderView: abid:'+ab.attr('data-artboard-recid'));ab.find(".tn-elem").each(function(){t396_elem__renderView(jQuery(this))})}
function t396_ab__filterUpdate(ab){var filter=ab.find('.t396__filter');var c1=filter.attr('data-filtercolor-rgb');var c2=filter.attr('data-filtercolor2-rgb');var o1=filter.attr('data-filteropacity');var o2=filter.attr('data-filteropacity2');if((typeof c2=='undefined'||c2=='')&&(typeof c1!='undefined'&&c1!='')){filter.css("background-color","rgba("+c1+","+o1+")")}else if((typeof c1=='undefined'||c1=='')&&(typeof c2!='undefined'&&c2!='')){filter.css("background-color","rgba("+c2+","+o2+")")}else if(typeof c1!='undefined'&&typeof c2!='undefined'&&c1!=''&&c2!=''){filter.css({background:"-webkit-gradient(linear, left top, left bottom, from(rgba("+c1+","+o1+")), to(rgba("+c2+","+o2+")) )"})}else{filter.css("background-color",'transparent')}}
function t396_ab__getHeight(ab,ab_height){if(typeof ab_height=='undefined')ab_height=t396_ab__getFieldValue(ab,'height');ab_height=parseFloat(ab_height);var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(ab_height_vh!=''){ab_height_vh=parseFloat(ab_height_vh);if(isNaN(ab_height_vh)===!1){var ab_height_vh_px=parseFloat(window.tn.window_height*parseFloat(ab_height_vh/100));if(ab_height<ab_height_vh_px){ab_height=ab_height_vh_px}}}
return(ab_height)}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(el,value){if(typeof value=='undefined')value=parseFloat(t396_elem__getFieldValue(el,'width'));var el_widthunits=t396_elem__getFieldValue(el,'widthunits');if(el_widthunits=='%'){var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(window.tn.window_width*parseFloat(parseInt(value)/100))}else{value=parseFloat(window.tn.grid_width*parseFloat(parseInt(value)/100))}}
return(value)}
function t396_elem__getHeight(el,value){if(typeof value=='undefined')value=t396_elem__getFieldValue(el,'height');value=parseFloat(value);if(el.attr('data-elem-type')=='shape'||el.attr('data-elem-type')=='video'||el.attr('data-elem-type')=='html'||el.attr('data-elem-type')=='gallery'){var el_heightunits=t396_elem__getFieldValue(el,'heightunits');if(el_heightunits=='%'){var ab=el.parent();var ab_min_height=parseFloat(ab.attr('data-artboard-proxy-min-height'));var ab_max_height=parseFloat(ab.attr('data-artboard-proxy-max-height'));var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(ab_max_height*parseFloat(value/100))}else{value=parseFloat(ab_min_height*parseFloat(value/100))}}}else if(el.attr('data-elem-type')=='button'){value=value}else{value=parseFloat(el.innerHeight())}
return(value)}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(window.tn_comments==1)console.log(str)}
function t396_setUpTooltip_desktop(el,pinEl,tipEl){var timer;pinEl.mouseover(function(){jQuery('.tn-atom__tip_visible').each(function(){var thisTipEl=jQuery(this).parents('.t396__elem');if(thisTipEl.attr('data-elem-id')!=el.attr('data-elem-id')){t396_hideTooltip(thisTipEl,jQuery(this))}});clearTimeout(timer);if(tipEl.css('display')=='block'){return}
t396_showTooltip(el,tipEl)});pinEl.mouseout(function(){timer=setTimeout(function(){t396_hideTooltip(el,tipEl)},300)})}
function t396_setUpTooltip_mobile(el,pinEl,tipEl){pinEl.on('click',function(e){if(tipEl.css('display')=='block'&&jQuery(e.target).hasClass("tn-atom__pin")){t396_hideTooltip(el,tipEl)}else{t396_showTooltip(el,tipEl)}});var id=el.attr("data-elem-id");jQuery(document).click(function(e){var isInsideTooltip=(jQuery(e.target).hasClass("tn-atom__pin")||jQuery(e.target).parents(".tn-atom__pin").length>0);if(isInsideTooltip){var clickedPinId=jQuery(e.target).parents(".t396__elem").attr("data-elem-id");if(clickedPinId==id){return}}
t396_hideTooltip(el,tipEl)})}
function t396_hideTooltip(el,tipEl){tipEl.css('display','');tipEl.css({"left":"","transform":"","right":""});tipEl.removeClass('tn-atom__tip_visible');el.css('z-index','')}
function t396_showTooltip(el,tipEl){var pos=el.attr("data-field-tipposition-value");if(typeof pos=='undefined'||pos==''){pos='top'};var elSize=el.height();var elTop=el.offset().top;var elBottom=elTop+elSize;var elLeft=el.offset().left;var elRight=el.offset().left+elSize;var winTop=jQuery(window).scrollTop();var winWidth=jQuery(window).width();var winBottom=winTop+jQuery(window).height();var tipElHeight=tipEl.outerHeight();var tipElWidth=tipEl.outerWidth();var padd=15;if(pos=='right'||pos=='left'){var tipElRight=elRight+padd+tipElWidth;var tipElLeft=elLeft-padd-tipElWidth;if((pos=='right'&&tipElRight>winWidth)||(pos=='left'&&tipElLeft<0)){pos='top'}}
if(pos=='top'||pos=='bottom'){var tipElRight=elRight+(tipElWidth/2-elSize/2);var tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padd);tipEl.css({"left":"auto","transform":"none","right":rightOffset+"px"})}
if(tipElLeft<0){var leftOffset=-(elLeft-padd);tipEl.css({"left":leftOffset+"px","transform":"none"})}}
if(pos=='top'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos=='bottom'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
tipEl.attr('data-tip-pos',pos);tipEl.css('display','block');tipEl.addClass('tn-atom__tip_visible');el.css('z-index','1000')}
function t396_hex2rgba(hexStr,opacity){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t410_init(recid){var el=jQuery('#rec'+recid);var firstimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-first");var firstimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-first");var firstimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-first");var secondimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-second");var secondimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-second");var secondimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-second");t410_onObjLoad('juxtapose',function(){new juxtapose.JXSlider('#t410-juxtapose__'+recid,[{src:firstimgurl,label:firstimgdescr},{src:secondimgurl,label:secondimgdescr}],{animate:!1,showLabels:!0,showCredits:!1,startingPosition:'50%',makeResponsive:!0,callback:function(){if(firstimgalt){el.find('.t410__wrapper .jx-image.jx-left img').attr('alt',firstimgalt)}
if(secondimgalt){el.find('.t410__wrapper .jx-image.jx-right img').attr('alt',secondimgalt)}
if(window.isMobile){el.find('.t410__wrapper').append('<div class="t410__mobile_left"></div><div class="t410__mobile_right"></div>');var hanlerWidth=el.find('.jx-handle').width(),leftSide=el.find('.jx-image.jx-left'),rightSide=el.find('.jx-image.jx-right'),leftWidth=leftSide.width()-hanlerWidth/2,rightWidth=rightSide.width()-hanlerWidth/2,wrapper=el.find('.t410__wrapper'),mobileLeft=el.find('.t410__mobile_left'),mobileRight=el.find('.t410__mobile_right');mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth);wrapper.on('touchend',function(){leftWidth=leftSide.width()-hanlerWidth/2;rightWidth=rightSide.width()-hanlerWidth/2;mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth)})}}})});el.find('.t410').bind('displayChanged',function(){window.juxtapose.sliders.forEach(function(obj){if(obj.selector==='#t410-juxtapose__'+recid){console.log(obj);obj.setWrapperDimensions();return}})})}
function t410_onObjLoad(objName,okFunc,time){if(typeof window[objName]==='object'){okFunc()}else{var timerId=setTimeout(function checkFuncExist(){if(typeof window[objName]==='object'){okFunc();return}
timerId=setTimeout(checkFuncExist,time||100)})}}
function t412_init(recid){var rec=jQuery('#rec'+recid);if(rec.find('a[href^="#order"]')){rec.find('a[href^="#order"]').on('click',function(e){var $linkelem=jQuery(this);var $jspaybox=jQuery('.js-payment-systembox');t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox);$jspaybox.css('margin-top','0');$jspaybox.css('margin-left','0');jQuery(window).resize(function(){if($jspaybox.css('display')=='block'&&$linkelem){t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox)}})})}}
function t412_setCoordinateToPaymentBox(event,$linkelem,$jspaybox){var oldTopCoord=0;var newTopCoord=0;var offset=$linkelem.offset();var top=offset.top+$linkelem.parents('.t412__col').height()-$jspaybox.height();var left=offset.left+$linkelem.parents('.t412__col').width()/2-$jspaybox.width()/2;oldTopCoord=$jspaybox.css('top');$jspaybox.css('top',top+'px');$jspaybox.css('left',left+'px');newTopCoord=$jspaybox.css('top');if(parseInt(oldTopCoord)-parseInt(newTopCoord)==21){$jspaybox.css('top',(top+21)+'px')}}
function t412_unifyHeights(recid){var el=jQuery("#rec"+recid);el.find('.t412__descr').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox2=0;jQuery('.t412__descr',this).each(function(){if(jQuery(this).height()>highestBox2)highestBox2=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__descr',this).css('height',highestBox2)}else{jQuery('.t412__descr',this).css('height',"auto")}});el.find('.t412__title').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox3=0;jQuery('.t412__title',this).each(function(){if(jQuery(this).height()>highestBox3)highestBox3=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__title',this).css('height',highestBox3)}else{jQuery('.t412__title',this).css('height',"auto")}});el.find('.t412__wrapper').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox=0;jQuery('.t412__wrapper',this).each(function(){if(jQuery(this).height()>highestBox)highestBox=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__wrapper',this).css('height',highestBox)}else{jQuery('.t412__wrapper',this).css('height',"auto")}})}
function t449_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t449").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.hasClass('t449__beforeready')){el.finish();el.removeClass("t449__beforeready")}}else{el.stop();el.addClass("t449__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if(jQuery(window).scrollTop()+jQuery(window).height()>=jQuery(document).height()-hideoffset){if(!el.hasClass('t449__beforeready')){el.finish();el.addClass("t449__beforeready")}}else{if(appearoffset!=""){if(jQuery(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t449__beforeready")}}else{el.stop();el.removeClass("t449__beforeready")}}}})}}
function t450_showMenu(recid){var el=jQuery('#rec'+recid);jQuery('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');jQuery('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*="#"]').click(function(){var url=jQuery(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
if(jQuery(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
t450_closeMenu()});jQuery(document).keydown(function(e){if(e.keyCode===27){jQuery('body').removeClass('t390__body_popupshowed');jQuery('.t390').removeClass('t390__popup_show')}});el.find('.t-menu__link-item').each(function(){var $this=jQuery(this);if($this.hasClass('t966__tm-link')){$this.on('click',function(){setTimeout(function(){t450_checkSize(recid)},300)})}
if($this.hasClass('t978__tm-link')){$this.on('click',function(){t450_checkSize(recid);el.find(".t978__menu-link").on('click',function(){t450_checkSize(recid)})})}});t450_highlight()}
function t450_closeMenu(){jQuery('body').removeClass('t450__body_menushowed');jQuery('.t450').removeClass('t450__menu_show');jQuery('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=jQuery('#rec'+recid).find('.t450');var windowheight=jQuery(window).height()-80;setTimeout(function(){var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')}else{el.removeClass('t450__overflowed');el.find(".t450__container").css('height','')}})}
function t450_appearMenu(recid){var el=jQuery('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if(jQuery(window).scrollTop()+jQuery(window).height()>=jQuery(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if(jQuery(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=jQuery('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){jQuery('.r').on('click','a[href="'+hook+'"]',function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
jQuery('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)});if(window.isMobile){jQuery('#rec'+recid).find('.t-menu__link-item').each(function(){var $this=jQuery(this);if($this.hasClass('t450__link-item_submenu')){$this.on('click',function(){t450_checkSize(recid)})}})}
jQuery(window).on('resize',function(){t450_checkSize(recid)})}
function t450_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t450__menu a").removeClass("t-active");jQuery(".t450__menu a[href='"+url+"']").addClass("t-active");jQuery(".t450__menu a[href='"+url+"/']").addClass("t-active");jQuery(".t450__menu a[href='"+pathname+"']").addClass("t-active");jQuery(".t450__menu a[href='/"+pathname+"']").addClass("t-active");jQuery(".t450__menu a[href='"+pathname+"/']").addClass("t-active");jQuery(".t450__menu a[href='/"+pathname+"/']").addClass("t-active");if(hash!==""){jQuery(".t450__menu a[href='"+hash+"']").addClass("t-active")}}
function t456_setListMagin(recid,imglogo){if(jQuery(window).width()>980){var t456__menu=jQuery('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t456__list_item a[href='"+url+"']").addClass("t-active");jQuery(".t456__list_item a[href='"+url+"/']").addClass("t-active");jQuery(".t456__list_item a[href='"+pathname+"']").addClass("t-active");jQuery(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");jQuery(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");jQuery(".t456__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t456_navLinks=jQuery("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=jQuery(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref(jQuery(this));if(typeof t456_cursection!=="undefined"){if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=jQuery(this)}});t456_updateSectionsOffsets(t456_sections);t456_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});jQuery(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));jQuery('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId);t456_navLinks.click(function(){var t456_clickedSection=t456_getSectionByHref(jQuery(this));if(typeof t456_clickedSection!=="undefined"&&!jQuery(this).hasClass("tooltipstered")&&typeof t456_clickedSection.attr("id")!="undefined"){t456_navLinks.removeClass('t-active');jQuery(this).addClass('t-active');t456_clickedSectionId=t456_getSectionByHref(jQuery(this)).attr("id")}});jQuery(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t456_curSection=jQuery(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var hash=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');var block=jQuery(".r[id='"+hash+"']");var anchor=jQuery(".r[data-record-type='215']").has("a[name='"+hash+"']");if(curlink.is('[href*="#rec"]')){return block}else if(anchor.length===1){return anchor}else{return undefined}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=jQuery(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
jQuery(t456_sections).each(function(e){var t456_curSection=jQuery(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{jQuery(".t456").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=jQuery(window).width(),el=jQuery("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);jQuery(this).toggleClass("t456_opened")});jQuery(window).bind('resize',t_throttle(function(){window_width=jQuery(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t602_init(recid){jQuery(window).on('scroll',t_throttle(function(){t602_setProgressBarWidth(recid)},100))}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=jQuery(window).scrollTop(),t602_docHeight=jQuery(document).height(),t602_winHeight=jQuery(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;jQuery(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t668_init(recid){var el=jQuery('#rec'+recid);var toggler=el.find(".t668__header");var accordion=el.find('.t668__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t668__opened").next().slideUp()}
jQuery(this).toggleClass("t668__opened");jQuery(this).next().slideToggle();if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=jQuery('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if(jQuery(this).attr('data-slider-video-type')=='youtube'){var url=jQuery(this).attr('data-slider-video-url');jQuery(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen allow=\"autoplay\"></iframe>")}
if(jQuery(this).attr('data-slider-video-type')=='vimeo'){var url=jQuery(this).attr('data-slider-video-url');var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;jQuery(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+id+hash+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
jQuery(this).next().css('z-index','3')})}
function t670_hide(recid){var el=jQuery('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=jQuery('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=jQuery(this).attr('data-slider-image-width');var height=jQuery(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;jQuery(this).css('padding-bottom',padding+'%')})}
function t674_init(recid){var el=jQuery("#rec"+recid);el.find('.t674__img-holder').on('load',function(){var delay=0;if(jQuery('#allrecords').attr('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){jQuery('body').addClass('t674__body_with-bg')},delay)}).each(function(){if(this.complete)jQuery(this).trigger('load')})}
function t686_init(recid){var el=jQuery("#rec"+recid);setTimeout(function(){t686_setHeight(recid)},100);jQuery(window).on('resize',t_throttle(function(){t686_setHeight(recid)}));el.find('.t686').bind('displayChanged',function(){t686_setHeight(recid)})}
function t686_setHeight(recid){var el=jQuery('#rec'+recid+' .t686');var ratio=el.attr('data-tile-ratio');var ratioHeight=el.find('.t686__col').width()*ratio;var largestHeight=0;el.find('.t686__row').each(function(){jQuery('.t686__table',this).each(function(){var curCol=jQuery(this);var curColHeight=curCol.find(".t686__textwrapper").outerHeight();if(jQuery(this).find(".t686__cell").hasClass("t686__button-bottom")){curColHeight+=curCol.find(".t686__button-container").outerHeight()}
if(curColHeight>largestHeight){largestHeight=curColHeight}});if(jQuery(window).width()>=960){if(largestHeight>ratioHeight){jQuery('.t686__table',this).css('height',largestHeight)}else{jQuery('.t686__table',this).css('height',ratioHeight)}
jQuery('.t686__table',this).css('min-height','auto')}else{jQuery('.t686__table',this).css('min-height',ratioHeight);jQuery('.t686__table',this).css('height','')}
if(t686_GetIEVersion()>0){var curRowHeight=jQuery('.t686__table',this).css('height');jQuery('.t686__bg',this).css('height',curRowHeight);jQuery('.t686__overlay',this).css('height',curRowHeight)}})}
function t686_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t706_onSuccessCallback(t706_form){jQuery(".t706__cartwin-products").slideUp(10,function(){});jQuery(".t706__cartwin-bottom").slideUp(10,function(){});jQuery(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t764_init(recid){var el=jQuery('#rec'+recid);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'),10);sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)});el.find('.t764').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}
function t774_init(recid){t774_unifyHeights(recid);jQuery(window).on('resize',t_throttle(function(){t774_unifyHeights(recid)},200));jQuery(".t774").on("displayChanged",function(){t774_unifyHeights(recid)});jQuery(window).on('load',function(){t774_unifyHeights(recid)});setTimeout(function(){t774__updateLazyLoad(recid)},500)}
function t774__updateLazyLoad(recid){var scrollContainer=jQuery("#rec"+recid+" .t774__container_mobile-flex");var curMode=jQuery(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"&&window.lazy==="y"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}}
function t774_unifyHeights(recid){var t774_el=jQuery('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if(jQuery(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if(jQuery(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}else{if(jQuery(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=jQuery(this).find(".t774__textwrapper"),t774_curBtns=jQuery(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t776_initProductQuantity(recid)}
jQuery('body').trigger('twishlist_addbtn')},500)}
function t776_initProductQuantity(recid){var el=jQuery('#rec'+recid);var productList=el.find(".t776__col, .t776__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents(jQuery(product))})}
function t776__showMore(recid){var el=jQuery('#rec'+recid).find(".t776");var showmore=el.find('.t776__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t776__dict('loadmore'))}
showmore.show();el.find('.t776__col').hide();var cards_size=el.find('.t776__col').size();var x=cards_count;var y=cards_count;t776__showSeparator(el,x);el.find('.t776__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t776__col:lt('+x+')').show();if(x==cards_size){showmore.hide()}
t776__showSeparator(el,x);if(jQuery('#rec'+recid).find('[data-buttons-v-align]')[0]){t776__alignButtons(recid)}
if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t776__showSeparator(el,x){el.find('.t776__separator_number').addClass('t776__separator_hide');el.find('.t776__separator_hide').each(function(){if(jQuery(this).attr('data-product-separator-number')<=x){jQuery(this).removeClass('t776__separator_hide')}})}
function t776__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t776__alignButtons_init(recid){var el=jQuery('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t776__alignButtons(recid);jQuery(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t776__alignButtons(recid)}));el.find('.t776').bind('displayChanged',function(){t776__alignButtons(recid)});if($isMobile){jQuery(window).on('orientationchange',function(){t776__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t776__alignButtons(recid){var rec=jQuery('#rec'+recid);var wrappers=rec.find('.t776__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=jQuery(window).width()<=480;var tableView=jQuery(window).width()<=960&&jQuery(window).width()>480;var mobileOneRow=jQuery(window).width()<=960&&rec.find('.t776__container_mobile-flex')[0]?true:!1;var mobileTwoItemsInRow=jQuery(window).width()<=480&&rec.find('.t776 .mobile-two-columns')[0]?true:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];jQuery.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
jQuery.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t776__hoverZoom_init(recid){if(isMobile){return}
var rec=jQuery('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
jQuery.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid)},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t776__updateLazyLoad(recid){var scrollContainer=jQuery("#rec"+recid+" .t776__container_mobile-flex");var curMode=jQuery(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=jQuery('#rec'+recid);rec.find('[href^="#prodpopup"]').each(function(e){var el_popup=rec.find('.t-popup');var el_prod=jQuery(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');jQuery(".r").find('a[href$="#!/tproduct/'+recid+'-'+lid_prod+'"]').click(function(e){if(rec.find('[data-product-lid='+lid_prod+']').length){rec.find('[data-product-lid='+lid_prod+'] [href^="#prodpopup"]').triggerHandler('click')}})});rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=jQuery(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();if(jQuery(e.target).hasClass('t1002__addBtn')||jQuery(e.target).parents().hasClass('t1002__addBtn')){return}
t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=jQuery(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if(jQuery('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=jQuery('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=jQuery('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var el=jQuery('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);jQuery('body').addClass('t-body_popupshowed');jQuery('body').trigger('twishlist_addbtn');el.find('.t-popup').mousedown(function(e){var windowWidth=jQuery(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});jQuery(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}});if(window.isSafari){setTimeout(function(){el.find('.t-popup').scrollTop(1)})}}
function t776_closePopup(){jQuery('body').removeClass('t-body_popupshowed');jQuery('body').trigger('twishlist_addbtn');jQuery('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){jQuery(".t-popup").scrollTop(0);jQuery('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=jQuery('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}
function t827_init(recid){var rec=jQuery('#rec'+recid);var grid=rec.find('.t827__grid');var sizer=rec.find('.t827__grid-sizer');var item=rec.find('.t827__grid-item');var images=rec.find('.t827__grid img');var overlay=rec.find('.t827__overlay');var startContainerWidth=rec.find('.t827__grid-sizer').width();t827_reverse(grid,item);images.load(function(){t827_initMasonry(rec,recid,grid);setTimeout(function(){t827_showOverlay(overlay,item)},500)});if(overlay.hasClass('t827__overlay_preview')){setTimeout(function(){t827_showOverlay(overlay,item)},1000)}
t827_initMasonry(rec,recid,grid);jQuery(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}));rec.find('.t827').bind('displayChanged',function(){t827_initMasonry(rec,recid,grid);t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)});setTimeout(function(){t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)})}
function t827_reverse(grid,item){if(grid.hasClass('t827__grid_reverse')){grid.append(function(){return jQuery(this).children().get().reverse()})}}
function t827_initMasonry(rec,recid,grid){var $grid=grid;var gutterSizerWidth=rec.find('.t827__gutter-sizer').width();var gutterElement=rec.find('.t827__gutter-sizer').width()==40?39:'#rec'+recid+' .t827__gutter-sizer';t_onFuncLoad('imagesLoaded',function(){$grid.imagesLoaded(function(){$grid.masonry({itemSelector:'#rec'+recid+' .t827__grid-item',columnWidth:'#rec'+recid+' .t827__grid-sizer',gutter:gutterElement,isFitWidth:!0,transitionDuration:0})})})}
function t827_showOverlay(overlay,item){if(jQuery(window).width()>=1024){overlay.css('display','block')}else{item.click(function(){if(jQuery(this).find('.t827__overlay').css('opacity')=='0'){overlay.css('opacity','0');jQuery(this).find('.t827__overlay').css('opacity','1')}else{jQuery(this).find('.t827__overlay').css('opacity','0')}})}}
function t827_calcColumnWidth(rec,startcontainerwidth,grid,sizer,item){var containerWidth=rec.find('.t827__container').width();var sizerWidth=rec.find('.t827__grid-sizer').width();var itemWidth=rec.find('.t827__grid-item').width();var gutterSizerWidth=rec.find('.t827__gutter-sizer').width()==40?39:rec.find('.t827__gutter-sizer').width();var columnAmount=Math.round(containerWidth/startcontainerwidth);var newSizerWidth=((containerWidth-gutterSizerWidth*(columnAmount-1))/columnAmount);if(containerWidth>=itemWidth){sizer.css('width',newSizerWidth);item.css('width',newSizerWidth)}else{grid.css('width','100%');sizer.css('width','100%');item.css('width','100%')}}
function t851_init(recid){var rec=jQuery('#rec'+recid+' .t851');t851_updateLazyLoad(recid)}
function t851_updateLazyLoad(recid){var scrollContainer=jQuery("#rec"+recid+" .t851__container_mobile-flex");var curMode=jQuery(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}}
function t959__init(recid){var el=jQuery('#rec'+recid);t959__updateLazyLoad(recid);jQuery(window).on('resize',t_throttle(function(){t959_unifyHeights(recid)}));jQuery(window).on('load',function(){t959_unifyHeights(recid)});el.find('.t959').on('displayChanged',t_throttle(function(){t959_unifyHeights(recid)}))}
function t959__updateLazyLoad(recid){var scrollContainer=jQuery("#rec"+recid+" .t959__container_mobile-flex");var curMode=jQuery(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"&&window.isMobile){scrollContainer.on('touchmove',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t959_unifyHeights(recid){jQuery('#rec'+recid+' .t959 .t959__container').each(function(){var highestBox=0,curwidth=jQuery(this).find('.t959__card-inner').width(),currow=jQuery(this),ratio=jQuery('#rec'+recid+' .t959__container').attr('data-ratio');var minHeightFromRatio;switch(ratio){case '16_9':minHeightFromRatio=curwidth*0.5625;break;case '4_3':minHeightFromRatio=curwidth*0.75;break;case '3_2':minHeightFromRatio=curwidth*0.6666;break;case '1_1':minHeightFromRatio=curwidth;break;case '2_3':minHeightFromRatio=curwidth*1.5;break;case '3_4':minHeightFromRatio=curwidth*1.3333;break;case '9_16':minHeightFromRatio=curwidth*1.7777;break}
currow.find('.t959__card-content').each(function(){var cardContent=jQuery(this);var titleHeight=cardContent.find('.t959__card-title').outerHeight(!0);var descrHeight=cardContent.find('.t959__card-desc').outerHeight(!0);var colHeight=titleHeight+descrHeight;if(colHeight>highestBox){highestBox=colHeight}});if(highestBox>minHeightFromRatio){currow.find('.t959__card-inner').css('padding-bottom',highestBox+'px')}else{currow.find('.t959__card-inner').css('padding-bottom','')}})}