function t142_checkSize(recid){var el=jQuery("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed")}}}
function t199_showMenu(recid){var el=jQuery('#rec'+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=jQuery(this),$body=jQuery('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=jQuery(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){jQuery(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$menu.find('.t199__menu-item-wrap .t-menusub__link-item').each(function(){var curUrl=jQuery(this).attr('href');jQuery(this).on('click',function(e){$body.removeClass(CLASS_MENU)})});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});jQuery(document).on('click',function(e){var clickedInsideMenu=jQuery(e.target).hasClass('t199__js__menu')||jQuery(e.target).parents('.t199__js__menu').length>0;if(!clickedInsideMenu){$body.removeClass(CLASS_MENU)}})});jQuery('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){jQuery('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=jQuery('#rec'+recid);var $header=el.find('.t199__js__header');var bgcolor=$header.css('background-color');var isScrolling=!1;var CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if(jQuery(window).scrollTop()>0){$header.addClass(CLASS_ACTIVE);$header.css('background-color','')}else{$header.removeClass(CLASS_ACTIVE);$header.css('background-color',bgcolor)}}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);jQuery(window).on('scroll',updateHeader);updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
jQuery(".t199__menu a[href='"+url+"']").addClass('t-active');jQuery(".t199__menu a[href='"+url+"/']").addClass('t-active');jQuery(".t199__menu a[href='"+pathname+"']").addClass('t-active');jQuery(".t199__menu a[href='/"+pathname+"']").addClass('t-active');jQuery(".t199__menu a[href='"+pathname+"/']").addClass('t-active');jQuery(".t199__menu a[href='/"+pathname+"/']").addClass('t-active')}
function t199_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t199_navLinks=jQuery('#rec'+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=jQuery(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref(jQuery(this));if(typeof t199_cursection.attr('id')!='undefined'){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr('id')]=jQuery(this)});t199_updateSectionsOffsets(t199_sections);jQuery(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));jQuery('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!jQuery(this).hasClass('tooltipstered')){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref(jQuery(this)).attr('id')].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref(jQuery(this)).attr('id')}});jQuery(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<t199_lastCall+t199_interval){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t199_curSection=jQuery(this);t199_curSection.attr('data-offset-top',t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return jQuery(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return jQuery(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=jQuery(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr('data-offset-top')>t199_scrollPosition+300){t199_navLinks.removeClass('t-active');return null}
jQuery(t199_sections).each(function(e){var t199_curSection=jQuery(this),t199_sectionTop=t199_curSection.attr('data-offset-top'),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(t199_scrollPosition+300>=t199_sectionTop||(t199_sections[0].attr('id')==t199_id&&t199_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t228__init(recid){var el=jQuery('#rec'+recid);var mobile=el.find('.t228__mobile');var fixedBlock=mobile.css('position')==='fixed'&&mobile.css('display')==='block';setTimeout(function(){el.on('click','.t-menusub__target-link',function(){if(isMobile){if(jQuery(this).hasClass('t-menusub__target-link_active')){el.find('.t228').trigger('overflow')}else{el.find('.t228').trigger('nooverflow')}}});el.find('.t-menu__link-item:not(.t-menusub__target-link):not(.tooltipstered):not(.t794__tm-link)').on('click',function(){if(jQuery(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
if(fixedBlock){mobile.trigger('click')}});el.find('.t-menusub__link-item').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__right_buttons_but .t-btn').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__positionabsolute');el.find('.t228').on('overflow',function(){t228_checkOverflow(recid)});el.find('.t228').on('nooverflow',function(){t228_checkNoOverflow(recid)})},500)}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t228__list_item a[href='"+url+"']").addClass("t-active");jQuery(".t228__list_item a[href='"+url+"/']").addClass("t-active");jQuery(".t228__list_item a[href='"+pathname+"']").addClass("t-active");jQuery(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");jQuery(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");jQuery(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){var el=jQuery('#rec'+recid);if(jQuery(window).width()>980){var t228_navLinks=el.find(".t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){setTimeout(function(){t228_catchScroll(t228_navLinks)},500)}}}
function t228_checkOverflow(recid){var el=jQuery('#rec'+recid);var menu=el.find('.t228');var winHeight=jQuery(window).height();if(menu.css('position')==='fixed'){menu.addClass('t228__overflow');menu[0].style.setProperty('height',winHeight-jQuery('.t228__mobile_container').outerHeight(!0)+'px','important')}}
function t228_checkNoOverflow(recid){var el=jQuery('#rec'+recid);var menu=el.find('.t228');var submenus=el.find('.t966__tooltip-menu_mobile');if(menu.css('position')==='fixed'){menu.removeClass('t228__overflow');menu[0].style.setProperty('height','auto')}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=[],t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=jQuery(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref(jQuery(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=jQuery(this)});t228_sections.sort(function(a,b){return b.offset().top-a.offset().top});t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var clickedSection=t228_getSectionByHref(jQuery(this));if(!jQuery(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');jQuery(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref(jQuery(this)).attr("id")}});jQuery(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return jQuery(".r[id='"+curLinkValue+"']")}else{return jQuery(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=jQuery(window).scrollTop();var t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!==0&&t228_clickedSectionId===null&&t228_sections[t228_sections.length-1].offset().top>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
jQuery(t228_sections).each(function(e){var t228_curSection=jQuery(this),t228_id=t228_curSection.attr('id'),t228_sectionTop=t228_curSection.offset().top,t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setWidth(recid){var el=jQuery('#rec'+recid);if(jQuery(window).width()>980){el.find(".t228").each(function(){var el=jQuery(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=jQuery(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth();if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}
el.find(".t228__centerside").removeClass("t228__centerside_hidden")}
function t228_setBg(recid){var el=jQuery('#rec'+recid);if(jQuery(window).width()>980){el.find(".t228").each(function(){var el=jQuery(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{el.find(".t228").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var el=jQuery('#rec'+recid);if(jQuery(window).width()>980){el.find(".t228").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");var topoffset=el.data('top-offset');if(topoffset&&parseInt(topoffset)>0){el.animate({"opacity":"1","top":topoffset+"px"},200,function(){})}else{el.animate({"opacity":"1","top":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}}})}}
function t228_changebgopacitymenu(recid){var el=jQuery('#rec'+recid);if(jQuery(window).width()>980){el.find(".t228").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var el=jQuery("#rec"+recid);var menu=el.find(".t228");var burger=el.find(".t228__mobile");burger.on('click',function(e){menu.fadeToggle(300);burger.toggleClass("t228_opened")});jQuery(window).bind('resize',t_throttle(function(){if(jQuery(window).width()>980){menu.fadeIn(0)}}))}
function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t229__list_item a[href='"+url+"']").addClass("t-active");jQuery(".t229__list_item a[href='"+url+"/']").addClass("t-active");jQuery(".t229__list_item a[href='"+pathname+"']").addClass("t-active");jQuery(".t229__list_item a[href='/"+pathname+"']").addClass("t-active");jQuery(".t229__list_item a[href='"+pathname+"/']").addClass("t-active");jQuery(".t229__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t229_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t229_navLinks=jQuery("#rec"+recid+" .t229__list_item a:not(.tooltipstered)[href*='#']");if(t229_navLinks.length>0){t229_catchScroll(t229_navLinks)}}}
function t229_catchScroll(t229_navLinks){var t229_clickedSectionId=null,t229_sections=new Array(),t229_sectionIdTonavigationLink=[],t229_interval=100,t229_lastCall,t229_timeoutId;t229_navLinks=jQuery(t229_navLinks.get().reverse());t229_navLinks.each(function(){var t229_cursection=t229_getSectionByHref(jQuery(this));if(typeof t229_cursection.attr("id")!="undefined"){t229_sections.push(t229_cursection)}
t229_sectionIdTonavigationLink[t229_cursection.attr("id")]=jQuery(this)});t229_updateSectionsOffsets(t229_sections);t229_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});jQuery(window).bind('resize',t_throttle(function(){t229_updateSectionsOffsets(t229_sections)},200));jQuery('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(t229_sections)});setInterval(function(){t229_updateSectionsOffsets(t229_sections)},5000);t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId);t229_navLinks.click(function(){var t229_clickedSection=t229_getSectionByHref(jQuery(this));if(!jQuery(this).hasClass("tooltipstered")&&typeof t229_clickedSection.attr("id")!="undefined"){t229_navLinks.removeClass('t-active');jQuery(this).addClass('t-active');t229_clickedSectionId=t229_getSectionByHref(jQuery(this)).attr("id")}});jQuery(window).scroll(function(){var t229_now=new Date().getTime();if(t229_lastCall&&t229_now<(t229_lastCall+t229_interval)){clearTimeout(t229_timeoutId);t229_timeoutId=setTimeout(function(){t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)},t229_interval-(t229_now-t229_lastCall))}else{t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)}})}
function t229_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t229_curSection=jQuery(this);t229_curSection.attr("data-offset-top",t229_curSection.offset().top)})}
function t229_getSectionByHref(curlink){var t229_curLinkValue=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return jQuery(".r[id='"+t229_curLinkValue+"']")}else{return jQuery(".r[data-record-type='215']").has("a[name='"+t229_curLinkValue+"']")}}
function t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId){var t229_scrollPosition=jQuery(window).scrollTop(),t229_valueToReturn=t229_clickedSectionId;if(t229_sections.length!=0&&t229_clickedSectionId==null&&t229_sections[t229_sections.length-1].attr("data-offset-top")>(t229_scrollPosition+300)){t229_navLinks.removeClass('t-active');return null}
jQuery(t229_sections).each(function(e){var t229_curSection=jQuery(this),t229_sectionTop=t229_curSection.attr("data-offset-top"),t229_id=t229_curSection.attr('id'),t229_navLink=t229_sectionIdTonavigationLink[t229_id];if(((t229_scrollPosition+300)>=t229_sectionTop)||(t229_sections[0].attr("id")==t229_id&&t229_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t229_clickedSectionId==null&&!t229_navLink.hasClass('t-active')){t229_navLinks.removeClass('t-active');t229_navLink.addClass('t-active');t229_valueToReturn=null}else{if(t229_clickedSectionId!=null&&t229_id==t229_clickedSectionId){t229_valueToReturn=null}}
return!1}});return t229_valueToReturn}
function t229_setPath(pageid){}
function t229_setBg(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t229").each(function(){var el=jQuery(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{jQuery(".t229").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t229_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery("#rec"+recid+" .t229").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t229_changeBgOpacityMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t229").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll)}else{el.css("background-color",bgcolor)}})}}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=jQuery('html, body');var target="";if(speed===undefined){speed=400}
try{target=jQuery(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=jQuery('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean(jQuery('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t280_showMenu(recid){var el=jQuery("#rec"+recid);el.find('.t280__burger, .t280__menu__bg, .t280__menu__item:not(".tooltipstered"):not(".t280__menu__item_submenu"), .t978__tooltip-menu_mobile').click(function(e){if(jQuery(this).is(".t280__menu__item.tooltipstered, .t794__tm-link")){return}
var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);var menuItemsLength=el.find('.t280__menu__item').length;var isAndroid=/(android)/i.test(navigator.userAgent);if(window.location.hash&&isChrome&&menuItemsLength>10&&isAndroid){setTimeout(function(){var hash=window.location.hash;window.location.hash="";window.location.hash=hash},50)}
if(!jQuery(this).is(".t978__tm-link, .t966__tm-link")){jQuery('body').toggleClass('t280_opened');el.find('.t280').toggleClass('t280__main_opened')}
t280_changeSize(recid);t280_highlight(recid);el.find(".t978__tm-link, .t966__tm-link").click(function(){t280_changeSize(recid);el.find(".t280__menu").css('transition','none');el.find(".t978__menu-link").click(function(){t280_changeSize(recid)})})});jQuery('.t280').bind('clickedAnchorInTooltipMenu',function(){jQuery('body').removeClass('t280_opened');el.find('.t280').removeClass('t280__main_opened')});if(el.find('.t-menusub__link-item')){el.find('.t-menusub__link-item').on('click',function(){jQuery('body').removeClass('t280_opened');el.find('.t280').removeClass('t280__main_opened')})}}
function t280_changeSize(recid){var el=jQuery("#rec"+recid);var div=el.find(".t280__menu").height();var bottomheight=el.find(".t280__bottom").height();var headerheight=el.find(".t280__container").height();var wrapper=el.find(".t280__menu__wrapper");var win=jQuery(window).height()-bottomheight-headerheight-160;if(div>win){wrapper.addClass('t280__menu_static')}
else{wrapper.removeClass('t280__menu_static')}}
function t280_changeBgOpacityMenu(recid){var window_width=jQuery(window).width();var record=jQuery("#rec"+recid);record.find(".t280__container__bg").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t280_appearMenu(){jQuery('.t280').each(function(){var el=jQuery(this);var appearoffset=el.attr('data-appearoffset');if(appearoffset!=''){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor(window.innerHeight*(parseInt(appearoffset)/100))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css('top','-50px');el.css('opacity','1');el.css('visibility','visible')}}else{el.stop();el.css('opacity','0');el.css('visibility','hidden')}}})}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
if(hash.substr(hash.length-1)=="/"){hash=hash.slice(0,-1)}
jQuery("#rec"+recid).find(".t280__menu a").removeClass("t-active");jQuery(".t280__menu a[href='"+url+"']").addClass("t-active");jQuery(".t280__menu a[href='"+url+"/']").addClass("t-active");jQuery(".t280__menu a[href='"+pathname+"']").addClass("t-active");jQuery(".t280__menu a[href='/"+pathname+"']").addClass("t-active");jQuery(".t280__menu a[href='"+pathname+"/']").addClass("t-active");jQuery(".t280__menu a[href='/"+pathname+"/']").addClass("t-active");if(hash!==""){jQuery(".t280__menu a[href='"+hash+"']").addClass("t-active");jQuery(".t280__menu a[href='/"+hash+"']").addClass("t-active");jQuery(".t280__menu a[href='"+hash+"/']").addClass("t-active");jQuery(".t280__menu a[href='/"+hash+"/']").addClass("t-active")}}
function t381_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t381").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("visibility","visible");el.animate({"opacity":"1"},300,function(){})}}else{el.stop();el.css("visibility","hidden")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if(jQuery(window).scrollTop()+jQuery(window).height()>=jQuery(document).height()-hideoffset){if(el.css('visibility')!='hidden'){el.finish();el.css("visibility","hidden")}}else{if(appearoffset!=""){if(jQuery(window).scrollTop()>=appearoffset){el.stop();el.css("visibility","visible")}}else{el.stop();el.css("visibility","visible")}}}})}}
function t396_init(recid){var data='';var res=t396_detectResolution();var ab=jQuery('#rec'+recid).find('.t396__artboard');window.tn_window_width=jQuery(window).width();window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;t396_initTNobj();t396_switchResolution(res);t396_updateTNobj();t396_artboard_build(data,recid);jQuery(window).resize(function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if($isMobile){var ww=jQuery(window).width();if(ww!=window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});jQuery(window).on("orientationchange",function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});jQuery(window).on('load',function(){t396_allelems__renderView(ab);if(typeof t_lazyload_update==='function'&&ab.css('overflow')==='auto'){ab.bind('scroll',t_throttle(function(){if(window.lazy==='y'||jQuery('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&ab.css('overflow')==='visible'){ab.css('overflow','hidden');setTimeout(function(){ab.css('overflow','visible')},1)}});var rec=jQuery('#rec'+recid);if(rec.attr('data-connect-with-tab')=='yes'){rec.find('.t396').bind('displayChanged',function(){var ab=rec.find('.t396__artboard');t396_allelems__renderView(ab)})}
if(isSafari)rec.find('.t396').addClass('t396_safari');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_getRotateValue(matrix){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var c=values[2];var d=values[3];var scale=Math.sqrt(a*a+b*b);var sin=b/scale;var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));return angle}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var isOpera=(!!window.opr&&!!opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var res=t396_detectResolution();var rec=jQuery('#rec'+recid);var $ab=rec.find('.t396__artboard');var abWidth=$ab.width();var updatedBlockHeight=Math.floor($ab.height()*window.tn_scale_factor);var ab_height_vh=t396_ab__getFieldValue($ab,'height_vh');window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;if(ab_height_vh!=''){var ab_min_height=t396_ab__getFieldValue($ab,'height');var ab_max_height=t396_ab__getHeight($ab);var scaledMinHeight=ab_min_height*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=ab_max_height)?scaledMinHeight:ab_max_height}
$ab.addClass('t396__artboard_scale');var scaleStr=isOnlyScalable?('transform: scale('+window.tn_scale_factor+') !important;'):('zoom: '+window.tn_scale_factor+';');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'<style>';$ab.append(styleStr);rec.find('.t396__elem').each(function(){var $el=jQuery(this);var containerProp=t396_elem__getFieldValue($el,'container');if(containerProp==='grid'){if(isOnlyScalable){var scaleProp='scale('+window.tn_scale_factor+')';var transformMatrix=$el.find('.tn-atom').css('transform');var rotatation=(transformMatrix&&transformMatrix!=='none')?t396_getRotateValue(transformMatrix):null;if(rotatation){if(!$el.find('.tn-atom__sbs-anim-wrapper').length)$el.find('.tn-atom').css('transform-origin','center');scaleProp=scaleProp+' rotate('+rotatation+'deg)'}
$el.find('.tn-atom').css('transform',scaleProp)}else{$el.css('zoom',window.tn_scale_factor);if($el.attr('data-elem-type')==='text'&&res<1200)$el.find('.tn-atom').css('-webkit-text-size-adjust','auto');$el.find('.tn-atom').css('transform-origin','center')}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var ww;var rec=jQuery('#rec'+recid);if($isMobile){ww=jQuery(window).width()}else{ww=window.innerWidth}
var res=t396_detectResolution();rec.find('.t396__scale-style').remove();if(!isOnlyScalable){rec.find('.t396__elem').css('zoom','');rec.find('.t396__elem .tn-atom').css('transform-origin','')}
var ab=rec.find('.t396__artboard');var abWidth=ab.width();window.tn_window_width=ww;window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;t396_switchResolution(res);t396_updateTNobj();t396_ab__renderView(ab);t396_allelems__renderView(ab);var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_detectResolution(){var ww;if($isMobile){ww=jQuery(window).width()}else{ww=window.innerWidth}
var res;res=1200;if(ww<1200){res=960}
if(ww<960){res=640}
if(ww<640){res=480}
if(ww<480){res=320}
return(res)}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=["320","480","640","960","1200"];window.tn.canvas_max_sizes=["480","640","960","1200",""];window.tn.ab_fields=["height","width","bgcolor","bgimg","bgattachment","bgposition","filteropacity","filtercolor","filteropacity2","filtercolor2","height_vh","valign"]}
function t396_updateTNobj(){tn_console('func: updateTNobj');if(typeof window.zero_window_width_hook!='undefined'&&window.zero_window_width_hook=='allrecords'&&jQuery('#allrecords').length){window.tn.window_width=parseInt(jQuery('#allrecords').width())}else{window.tn.window_width=parseInt(jQuery(window).width())}
if($isMobile){window.tn.window_height=parseInt(jQuery(window).height())}else{window.tn.window_height=parseInt(window.innerHeight)}
if(window.tn.curResolution==1200){window.tn.canvas_min_width=1200;window.tn.canvas_max_width=window.tn.window_width}
if(window.tn.curResolution==960){window.tn.canvas_min_width=960;window.tn.canvas_max_width=1200}
if(window.tn.curResolution==640){window.tn.canvas_min_width=640;window.tn.canvas_max_width=960}
if(window.tn.curResolution==480){window.tn.canvas_min_width=480;window.tn.canvas_max_width=640}
if(window.tn.curResolution==320){window.tn.canvas_min_width=320;window.tn.canvas_max_width=480}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=parseFloat((window.tn.window_width-window.tn.grid_width)/2)}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId="Don't call this twice without a uniqueId"}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(res,resmax){tn_console('func: switchResolution');if(typeof resmax=='undefined'){if(res==1200)resmax='';if(res==960)resmax=1200;if(res==640)resmax=960;if(res==480)resmax=640;if(res==320)resmax=480}
window.tn.curResolution=res;window.tn.curResolution_max=resmax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var ab=jQuery('#rec'+recid).find('.t396__artboard');t396_ab__renderView(ab);ab.find('.tn-elem').each(function(){var item=jQuery(this);if(item.attr('data-elem-type')=='text'){t396_addText(ab,item)}
if(item.attr('data-elem-type')=='image'){t396_addImage(ab,item)}
if(item.attr('data-elem-type')=='shape'){t396_addShape(ab,item)}
if(item.attr('data-elem-type')=='button'){t396_addButton(ab,item)}
if(item.attr('data-elem-type')=='video'){t396_addVideo(ab,item)}
if(item.attr('data-elem-type')=='html'){t396_addHtml(ab,item)}
if(item.attr('data-elem-type')=='tooltip'){t396_addTooltip(ab,item)}
if(item.attr('data-elem-type')=='form'){t396_addForm(ab,item)}
if(item.attr('data-elem-type')=='gallery'){t396_addGallery(ab,item)}});jQuery('#rec'+recid).find('.t396__artboard').removeClass('rendering').addClass('rendered');if(ab.attr('data-artboard-ovrflw')=='visible'){jQuery('#allrecords').css('overflow','hidden')}
if($isMobile){jQuery('#rec'+recid).append('<style>@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}</style>')}}
function t396_ab__renderView(ab){var fields=window.tn.ab_fields;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(ab,fields[i])}
var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(isScaled&&!isTildaModeEdit&&ab_height_vh!='')var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor;var offset_top=0;if(ab_min_height==ab_max_height||(scaledMinHeight&&scaledMinHeight>=ab_max_height)){offset_top=0}else{var ab_valign=t396_ab__getFieldValue(ab,'valign');if(ab_valign=='top'){offset_top=0}else if(ab_valign=='center'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)/2).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)/2).toFixed(1)}}else if(ab_valign=='bottom'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)).toFixed(1)}}else if(ab_valign=='stretch'){offset_top=0;ab_min_height=ab_max_height}else{offset_top=0}}
ab.attr('data-artboard-proxy-min-offset-top',offset_top);ab.attr('data-artboard-proxy-min-height',ab_min_height);ab.attr('data-artboard-proxy-max-height',ab_max_height);var filter=ab.find('.t396__filter');var carrier=ab.find('.t396__carrier');var abHeightVh=t396_ab__getFieldValue(ab,'height_vh');abHeightVh=parseFloat(abHeightVh);if(window.isMobile&&abHeightVh){var height=document.documentElement.clientHeight*parseFloat(abHeightVh/100);ab.css('height',height);filter.css('height',height);carrier.css('height',height)}}
function t396_addText(ab,el){tn_console('func: addText');var fields_str='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addImage(ab,el){tn_console('func: addImage');var fields_str='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);el.find('img').on("load",function(){t396_elem__renderViewOneField(el,'top');if(typeof jQuery(this).attr('src')!='undefined'&&jQuery(this).attr('src')!=''){setTimeout(function(){t396_elem__renderViewOneField(el,'top')},2000)}}).each(function(){if(this.complete)jQuery(this).trigger('load')});el.find('img').on('tuwidget_done',function(e,file){t396_elem__renderViewOneField(el,'top')})}
function t396_addShape(ab,el){tn_console('func: addShape');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addButton(ab,el){tn_console('func: addButton');var fields_str='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);return(el)}
function t396_addVideo(ab,el){tn_console('func: addVideo');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var viel=el.find('.tn-atom__videoiframe');var viatel=el.find('.tn-atom');viatel.css('background-color','#000');var vihascover=viatel.attr('data-atom-video-has-cover');if(typeof vihascover=='undefined'){vihascover=''}
if(vihascover=='y'){viatel.click(function(){var viifel=viel.find('iframe');if(viifel.length){var foo=viifel.attr('data-original');viifel.attr('src',foo)}
viatel.css('background-image','none');viatel.find('.tn-atom__video-play-link').css('display','none')})}
var autoplay=t396_elem__getFieldValue(el,'autoplay');var showinfo=t396_elem__getFieldValue(el,'showinfo');var loop=t396_elem__getFieldValue(el,'loop');var mute=t396_elem__getFieldValue(el,'mute');var startsec=t396_elem__getFieldValue(el,'startsec');var endsec=t396_elem__getFieldValue(el,'endsec');var tmode=jQuery('#allrecords').attr('data-tilda-mode');var url='';var viyid=viel.attr('data-youtubeid');if(typeof viyid!='undefined'&&viyid!=''){url='//youtube.com/embed/';url+=viyid+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo=='y'?'1':'0');if(loop=='y'){url+='&loop=1&playlist='+viyid}
if(startsec>0){url+='&start='+startsec}
if(endsec>0){url+='&end='+endsec}
if(mute=='y'){url+='&mute=1'}
if(vihascover=='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
viel.html('<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>');if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}
if(autoplay=='y'&&mute=='y'){viatel.trigger('click')}}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>')}}}
var vivid=viel.attr('data-vimeoid');if(typeof vivid!='undefined'&&vivid>0){url='//player.vimeo.com/video/';url+=vivid+'?color=ffffff&badge=0';if(showinfo=='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop=='y'){url+='&loop=1'}
if(mute=='y'){url+='&muted=1'}
if(vihascover=='y'){url+='&autoplay=1';viel.html('<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}}}}
function t396_addHtml(ab,el){tn_console('func: addHtml');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addTooltip(ab,el){tn_console('func: addTooltip');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var pinEl=el.find('.tn-atom__pin');var tipEl=el.find('.tn-atom__tip');var tipopen=el.attr('data-field-tipopen-value');if(isMobile||(typeof tipopen!='undefined'&&tipopen=='click')){t396_setUpTooltip_mobile(el,pinEl,tipEl)}else{t396_setUpTooltip_desktop(el,pinEl,tipEl)}
setTimeout(function(){jQuery('.tn-atom__tip-img').each(function(){var foo=jQuery(this).attr('data-tipimg-original');if(typeof foo!='undefined'&&foo!=''){jQuery(this).attr('src',foo)}})},3000)}
function t396_addForm(ab,el){tn_console('func: addForm');var fields_str='width,top,left,';fields_str+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addGallery(ab,el){tn_console('func: addForm');var fields_str='width,height,top,left,';fields_str+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_elem__setFieldValue(el,prop,val,flag_render,flag_updateui,res){if(res=='')res=window.tn.curResolution;if(res<1200&&prop!='zindex'){el.attr('data-field-'+prop+'-res-'+res+'-value',val)}else{el.attr('data-field-'+prop+'-value',val)}
if(flag_render=='render')elem__renderViewOneField(el,prop);if(flag_updateui=='updateui')panelSettings__updateUi(el,prop,val)}
function t396_elem__getFieldValue(el,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}
if(res==640){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}
if(res==480){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}
if(res==320){r=el.attr('data-field-'+prop+'-res-320-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}}}else{r=el.attr('data-field-'+prop+'-value')}
return(r)}
function t396_elem__renderView(el){tn_console('func: elem__renderView');var fields=el.attr('data-fields');if(!fields){return!1}
fields=fields.split(',');for(var i=0;i<fields.length;i++){t396_elem__renderViewOneField(el,fields[i])}}
function t396_elem__renderViewOneField(el,field){var value=t396_elem__getFieldValue(el,field);if(field=='left'){value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('left',parseFloat(value).toFixed(1)+'px')}
if(field=='top'){var ab=el.parents('.t396__artboard');value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('top',parseFloat(value).toFixed(1)+'px')}
if(field=='width'){value=t396_elem__getWidth(el,value);el.css('width',parseFloat(value).toFixed(1)+'px');var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){var pinSvgIcon=el.find('.tn-atom__pin-icon');if(pinSvgIcon.length>0){var pinSize=parseFloat(value).toFixed(1)+'px';pinSvgIcon.css({'width':pinSize,'height':pinSize})}
el.css('height',parseInt(value).toFixed(1)+'px')}
if(eltype=='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('width',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('width',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('width',parseFloat(value).toFixed(1)+'px')}}
if(field=='height'){var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){return}
value=t396_elem__getHeight(el,value);el.css('height',parseFloat(value).toFixed(1)+'px');if(eltype==='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('height',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('height',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('height',parseFloat(value).toFixed(1)+'px')}}
if(field=='container'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='width'||field=='height'||field=='fontsize'||field=='fontfamily'||field=='letterspacing'||field=='fontweight'||field=='img'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='inputs'){value=el.find('.tn-atom__inputs-textarea').val();try{t_zeroForms__renderForm(el,value)}catch(err){}}}
function t396_elem__convertPosition__Local__toAbsolute(el,field,value){var ab=el.parents('.t396__artboard');var blockVAlign=t396_ab__getFieldValue(ab,'valign');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=jQuery('#allrecords').attr('data-tilda-mode')=='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var el_axisy=t396_elem__getFieldValue(el,'axisy');value=parseInt(value);if(field=='left'){var el_container,offset_left,el_container_width,el_width;var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_left=window.tn.grid_offset_left;el_container_width=window.tn.grid_width}else{el_container='window';offset_left=0;el_container_width=window.tn.window_width}
var el_leftunits=t396_elem__getFieldValue(el,'leftunits');if(el_leftunits==='%'){value=t396_roundFloat(el_container_width*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offset_left+value}
var el_axisx=t396_elem__getFieldValue(el,'axisx');if(el_axisx==='center'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width/2-el_width/2+value}
if(el_axisx==='right'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width-el_width+value}}
if(field==='top'){var el_container,offset_top,el_container_height,el_height;var ab=el.parent();var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_top=parseFloat(ab.attr('data-artboard-proxy-min-offset-top'));el_container_height=parseFloat(ab.attr('data-artboard-proxy-min-height'))}else{el_container='window';offset_top=0;el_container_height=parseFloat(ab.attr('data-artboard-proxy-max-height'))}
var el_topunits=t396_elem__getFieldValue(el,'topunits');if(el_topunits==='%'){value=(el_container_height*(value/100))}
if(isScaledElement&&el_container!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&el_container!=='window'){offset_top=blockVAlign==='stretch'?0:(offset_top/window.tn_scale_factor)}
value=offset_top+value;var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);if(isScaled&&!isTildaModeEdit&&ab_height_vh!=''){var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor}
if(el_axisy==='center'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height/2-el_height/2+value}
if(el_axisy==='bottom'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height-el_height+value}}
return(value)}
function t396_ab__setFieldValue(ab,prop,val,res){if(res=='')res=window.tn.curResolution;if(res<1200){ab.attr('data-artboard-'+prop+'-res-'+res,val)}else{ab.attr('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(ab,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}
if(res==640){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}
if(res==480){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}
if(res==320){r=ab.attr('data-artboard-'+prop+'-res-320');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}}}else{r=ab.attr('data-artboard-'+prop)}
return(r)}
function t396_ab__renderViewOneField(ab,field){var value=t396_ab__getFieldValue(ab,field)}
function t396_allelems__renderView(ab){tn_console('func: allelems__renderView: abid:'+ab.attr('data-artboard-recid'));ab.find(".tn-elem").each(function(){t396_elem__renderView(jQuery(this))})}
function t396_ab__filterUpdate(ab){var filter=ab.find('.t396__filter');var c1=filter.attr('data-filtercolor-rgb');var c2=filter.attr('data-filtercolor2-rgb');var o1=filter.attr('data-filteropacity');var o2=filter.attr('data-filteropacity2');if((typeof c2=='undefined'||c2=='')&&(typeof c1!='undefined'&&c1!='')){filter.css("background-color","rgba("+c1+","+o1+")")}else if((typeof c1=='undefined'||c1=='')&&(typeof c2!='undefined'&&c2!='')){filter.css("background-color","rgba("+c2+","+o2+")")}else if(typeof c1!='undefined'&&typeof c2!='undefined'&&c1!=''&&c2!=''){filter.css({background:"-webkit-gradient(linear, left top, left bottom, from(rgba("+c1+","+o1+")), to(rgba("+c2+","+o2+")) )"})}else{filter.css("background-color",'transparent')}}
function t396_ab__getHeight(ab,ab_height){if(typeof ab_height=='undefined')ab_height=t396_ab__getFieldValue(ab,'height');ab_height=parseFloat(ab_height);var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(ab_height_vh!=''){ab_height_vh=parseFloat(ab_height_vh);if(isNaN(ab_height_vh)===!1){var ab_height_vh_px=parseFloat(window.tn.window_height*parseFloat(ab_height_vh/100));if(ab_height<ab_height_vh_px){ab_height=ab_height_vh_px}}}
return(ab_height)}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(el,value){if(typeof value=='undefined')value=parseFloat(t396_elem__getFieldValue(el,'width'));var el_widthunits=t396_elem__getFieldValue(el,'widthunits');if(el_widthunits=='%'){var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(window.tn.window_width*parseFloat(parseInt(value)/100))}else{value=parseFloat(window.tn.grid_width*parseFloat(parseInt(value)/100))}}
return(value)}
function t396_elem__getHeight(el,value){if(typeof value=='undefined')value=t396_elem__getFieldValue(el,'height');value=parseFloat(value);if(el.attr('data-elem-type')=='shape'||el.attr('data-elem-type')=='video'||el.attr('data-elem-type')=='html'||el.attr('data-elem-type')=='gallery'){var el_heightunits=t396_elem__getFieldValue(el,'heightunits');if(el_heightunits=='%'){var ab=el.parent();var ab_min_height=parseFloat(ab.attr('data-artboard-proxy-min-height'));var ab_max_height=parseFloat(ab.attr('data-artboard-proxy-max-height'));var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(ab_max_height*parseFloat(value/100))}else{value=parseFloat(ab_min_height*parseFloat(value/100))}}}else if(el.attr('data-elem-type')=='button'){value=value}else{value=parseFloat(el.innerHeight())}
return(value)}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(window.tn_comments==1)console.log(str)}
function t396_setUpTooltip_desktop(el,pinEl,tipEl){var timer;pinEl.mouseover(function(){jQuery('.tn-atom__tip_visible').each(function(){var thisTipEl=jQuery(this).parents('.t396__elem');if(thisTipEl.attr('data-elem-id')!=el.attr('data-elem-id')){t396_hideTooltip(thisTipEl,jQuery(this))}});clearTimeout(timer);if(tipEl.css('display')=='block'){return}
t396_showTooltip(el,tipEl)});pinEl.mouseout(function(){timer=setTimeout(function(){t396_hideTooltip(el,tipEl)},300)})}
function t396_setUpTooltip_mobile(el,pinEl,tipEl){pinEl.on('click',function(e){if(tipEl.css('display')=='block'&&jQuery(e.target).hasClass("tn-atom__pin")){t396_hideTooltip(el,tipEl)}else{t396_showTooltip(el,tipEl)}});var id=el.attr("data-elem-id");jQuery(document).click(function(e){var isInsideTooltip=(jQuery(e.target).hasClass("tn-atom__pin")||jQuery(e.target).parents(".tn-atom__pin").length>0);if(isInsideTooltip){var clickedPinId=jQuery(e.target).parents(".t396__elem").attr("data-elem-id");if(clickedPinId==id){return}}
t396_hideTooltip(el,tipEl)})}
function t396_hideTooltip(el,tipEl){tipEl.css('display','');tipEl.css({"left":"","transform":"","right":""});tipEl.removeClass('tn-atom__tip_visible');el.css('z-index','')}
function t396_showTooltip(el,tipEl){var pos=el.attr("data-field-tipposition-value");if(typeof pos=='undefined'||pos==''){pos='top'};var elSize=el.height();var elTop=el.offset().top;var elBottom=elTop+elSize;var elLeft=el.offset().left;var elRight=el.offset().left+elSize;var winTop=jQuery(window).scrollTop();var winWidth=jQuery(window).width();var winBottom=winTop+jQuery(window).height();var tipElHeight=tipEl.outerHeight();var tipElWidth=tipEl.outerWidth();var padd=15;if(pos=='right'||pos=='left'){var tipElRight=elRight+padd+tipElWidth;var tipElLeft=elLeft-padd-tipElWidth;if((pos=='right'&&tipElRight>winWidth)||(pos=='left'&&tipElLeft<0)){pos='top'}}
if(pos=='top'||pos=='bottom'){var tipElRight=elRight+(tipElWidth/2-elSize/2);var tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padd);tipEl.css({"left":"auto","transform":"none","right":rightOffset+"px"})}
if(tipElLeft<0){var leftOffset=-(elLeft-padd);tipEl.css({"left":leftOffset+"px","transform":"none"})}}
if(pos=='top'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos=='bottom'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
tipEl.attr('data-tip-pos',pos);tipEl.css('display','block');tipEl.addClass('tn-atom__tip_visible');el.css('z-index','1000')}
function t396_hex2rgba(hexStr,opacity){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t412_init(recid){var rec=jQuery('#rec'+recid);if(rec.find('a[href^="#order"]')){rec.find('a[href^="#order"]').on('click',function(e){var $linkelem=jQuery(this);var $jspaybox=jQuery('.js-payment-systembox');t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox);$jspaybox.css('margin-top','0');$jspaybox.css('margin-left','0');jQuery(window).resize(function(){if($jspaybox.css('display')=='block'&&$linkelem){t412_setCoordinateToPaymentBox(e,$linkelem,$jspaybox)}})})}}
function t412_setCoordinateToPaymentBox(event,$linkelem,$jspaybox){var oldTopCoord=0;var newTopCoord=0;var offset=$linkelem.offset();var top=offset.top+$linkelem.parents('.t412__col').height()-$jspaybox.height();var left=offset.left+$linkelem.parents('.t412__col').width()/2-$jspaybox.width()/2;oldTopCoord=$jspaybox.css('top');$jspaybox.css('top',top+'px');$jspaybox.css('left',left+'px');newTopCoord=$jspaybox.css('top');if(parseInt(oldTopCoord)-parseInt(newTopCoord)==21){$jspaybox.css('top',(top+21)+'px')}}
function t412_unifyHeights(recid){var el=jQuery("#rec"+recid);el.find('.t412__descr').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox2=0;jQuery('.t412__descr',this).each(function(){if(jQuery(this).height()>highestBox2)highestBox2=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__descr',this).css('height',highestBox2)}else{jQuery('.t412__descr',this).css('height',"auto")}});el.find('.t412__title').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox3=0;jQuery('.t412__title',this).each(function(){if(jQuery(this).height()>highestBox3)highestBox3=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__title',this).css('height',highestBox3)}else{jQuery('.t412__title',this).css('height',"auto")}});el.find('.t412__wrapper').css('height',"auto");jQuery('#rec'+recid+' .t412 .t-container').each(function(){var highestBox=0;jQuery('.t412__wrapper',this).each(function(){if(jQuery(this).height()>highestBox)highestBox=jQuery(this).height()});if(jQuery(window).width()>=960&&jQuery(this).is(':visible')){jQuery('.t412__wrapper',this).css('height',highestBox)}else{jQuery('.t412__wrapper',this).css('height',"auto")}})}
function t456_setListMagin(recid,imglogo){if(jQuery(window).width()>980){var t456__menu=jQuery('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
jQuery(".t456__list_item a[href='"+url+"']").addClass("t-active");jQuery(".t456__list_item a[href='"+url+"/']").addClass("t-active");jQuery(".t456__list_item a[href='"+pathname+"']").addClass("t-active");jQuery(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");jQuery(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");jQuery(".t456__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if(jQuery(window).width()>=960){var t456_navLinks=jQuery("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=jQuery(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref(jQuery(this));if(typeof t456_cursection!=="undefined"){if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=jQuery(this)}});t456_updateSectionsOffsets(t456_sections);t456_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});jQuery(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));jQuery('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId);t456_navLinks.click(function(){var t456_clickedSection=t456_getSectionByHref(jQuery(this));if(typeof t456_clickedSection!=="undefined"&&!jQuery(this).hasClass("tooltipstered")&&typeof t456_clickedSection.attr("id")!="undefined"){t456_navLinks.removeClass('t-active');jQuery(this).addClass('t-active');t456_clickedSectionId=t456_getSectionByHref(jQuery(this)).attr("id")}});jQuery(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){jQuery(sections).each(function(){var t456_curSection=jQuery(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var hash=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');var block=jQuery(".r[id='"+hash+"']");var anchor=jQuery(".r[data-record-type='215']").has("a[name='"+hash+"']");if(curlink.is('[href*="#rec"]')){return block}else if(anchor.length===1){return anchor}else{return undefined}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=jQuery(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
jQuery(t456_sections).each(function(e){var t456_curSection=jQuery(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=jQuery(document).height()-jQuery(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{jQuery(".t456").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(jQuery(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=jQuery(window).width();if(window_width>980){jQuery(".t456").each(function(){var el=jQuery(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if(jQuery(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=jQuery(window).width(),el=jQuery("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);jQuery(this).toggleClass("t456_opened")});jQuery(window).bind('resize',t_throttle(function(){window_width=jQuery(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t537_setHeight(recid){var t537__el=jQuery("#rec"+recid),t537__image=t537__el.find(".t537__bgimg:first"),t537__width=t537__image.attr("data-image-width"),t537__height=t537__image.attr("data-image-height"),t537__ratio=t537__height/t537__width,t537__padding=t537__ratio*100;jQuery("#rec"+recid+" .t537__bgimg").css("padding-bottom",t537__padding+"%")}
function t545_setHeight(recid){var el=jQuery('#rec'+recid);var t545_height=el.find('.t-container').attr("data-height");el.find('.t-container').each(function(){var highestBox=0;jQuery('.t545__col',this).each(function(){if(jQuery(this).height()>highestBox){highestBox=jQuery(this).height()}});if(t545_height>highestBox){highestBox=t545_height}
jQuery('.t545__textwrapper',this).css('height',highestBox);jQuery('.t545__blockimg',this).css('height',highestBox)})}
function t602_init(recid){jQuery(window).on('scroll',t_throttle(function(){t602_setProgressBarWidth(recid)},100))}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=jQuery(window).scrollTop(),t602_docHeight=jQuery(document).height(),t602_winHeight=jQuery(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;jQuery(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t698_fixcontentheight(id){var el=jQuery("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);el.find(".t-cover__container").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if(jQuery(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>jQuery(window).scrollTop()||(jQuery(document).height()-t698_inputsBottom)<(jQuery(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if(jQuery(window).height()>jQuery('.t-body').height()){jQuery('.t-tildalabel').animate({opacity:0},50)}},300)}else{jQuery('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t704_onSuccess(t704_form){var t704_inputsWrapper=t704_form.find('.t-form__inputsbox');var t704_inputsHeight=t704_inputsWrapper.height();var t704_inputsOffset=t704_inputsWrapper.offset().top;var t704_inputsBottom=t704_inputsHeight+t704_inputsOffset;var t704_targetOffset=t704_form.find('.t-form__successbox').offset().top;if(jQuery(window).width()>960){var t704_target=t704_targetOffset-200}else{var t704_target=t704_targetOffset-100}
if(t704_targetOffset>jQuery(window).scrollTop()||(jQuery(document).height()-t704_inputsBottom)<(jQuery(window).height()-100)){t704_inputsWrapper.addClass('t704__inputsbox_hidden');setTimeout(function(){if(jQuery(window).height()>jQuery('.t-body').height()){jQuery('.t-tildalabel').animate({opacity:0},50)}},300)}else{jQuery('html, body').animate({scrollTop:t704_target},400);setTimeout(function(){t704_inputsWrapper.addClass('t704__inputsbox_hidden')},400)}
var successurl=t704_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t887_init(recid){var el=jQuery('#rec'+recid);var block=el.find('.t887');var closeIcon=el.find('.t887__icon-close');var storageItem=block.attr("data-storage-item");var lastOpen=null;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(e){console.log('Your web browser does not support localStorage.')}}
if(lastOpen==null){block.removeClass('t887_closed')}
closeIcon.click(function(e){block.addClass('t887_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(e){console.log('Your web browser does not support localStorage.')}}
e.preventDefault()})}